server:
  port: 8089
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://BAW-USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: servicemgmt-service
          uri: lb://baw-servicemgmt-service
          predicates:
            - Path=/api/service/**
        - id: location-service
          uri: lb://baw-location-service
          predicates:
            - Path=/api/location/**
        - id: rating-service
          uri: lb://baw-rating-service
          predicates:
            - Path=/api/rating/** 
        - id: booking-service
          uri: lb://baw-booking-service
          predicates:
            - Path=/api/booking/**
        - id: payment-service
          uri: lb://baw-payment-service
          predicates:
            - Path=/api/payment/**       
