server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=Asia/Kolkata
    username: root
    password: pass
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
      show-sql: true
    logging:
      level:
        com.carwash: DEBUG
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      pattern:
        console: '%-5level- %msg%n'